---
- name: Remove old docker versions
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure Docker Edge repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-ce.repo'
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Install Docker
  package:
    name: docker-ce
    state: present
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true

- name: Install containerd separately (CentOS 8)
  package:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present
  when: ansible_distribution_major_version | int == 8
  notify: restart docker


